defaults:
    - _self_
    - dataset: xor
    - selectors: default
    - stability_metric: default
    - stability_reduced: top2
feature:
    informative_prefix: "informative_"
    informative_per_label_prefix: "informative_for_labels_"
output:
    root: "output"
    temporary: "temporary"
    execution_output:
        root: "[to be set dynamically]"
        selection_performance: "selection_performance"
        feature_erasure: "feature_erasure"
        predictive_performance: "predictive_performance"
        weighted_tsne: "weighted_tsne"
        stability: "stability"
        execution_time: "execution_time"
        informative_features: "informative_features"
        raw_selection: "raw_selection"
        log_file: "log.txt"
    metrics:
        - pifs
        - stability
        - reduced_stability