root: "dataset"
filename: "Liver_GSE22405.csv"
label_column: "type"
ignored_columns: 
  - "samples"
test_percentage: 15
k_fold: 11
k_fold_repeat: 1
regularization_lambda: 0.0025
lime_k: 50
shap_k: 50
shap_representative_k: 50
sage_k: 50
sage_representative_k: 50
relieff_k: 50
lasso_regularization: 0.01
data_type: "float32"
label_type: "string"
batch_size: 8
epochs: 800
learning_rate: 0.001
model: 1
scale: true
normalize: false
jaccard_k: 30
random_seed: 42
external_predictor_k: 100
external_predictor_step: 1
erasure_k: 100
erasure_step: 1