root: "dataset"
filename: "synth_3classes_3000samples_300features_30informative_10informativeperclass.csv"
label_column: "class"
ignored_columns: 
  - "id"
test_percentage: 20
k_fold: 11
k_fold_repeat: 1
regularization_lambda: 0.01
lime_k: 1000
shap_k: 1000
shap_representative_k: 1000
sage_k: 100
sage_representative_k: 100
relieff_k: 1000
lasso_regularization: 0.01
data_type: "float32"
label_type: "long"
batch_size: 32
epochs: 300
learning_rate: 0.001
model: 1
scale: true
normalize: false
jaccard_k: 30
random_seed: 42
external_predictor_k: 50
external_predictor_step: 10
erasure_k: 50
erasure_step: 1