root: "dataset"
filename: "xor_500samples_50features.csv"
label_column: "class"
ignored_columns: 
  - "id"
test_percentage: 20
k_fold: 11
k_fold_repeat: 1
regularization_lambda: 0.01
lime_k: 1000
shap_k: 1000
shap_representative_k: 1000
relieff_k: 1000
lasso_regularization: 0.01
data_type: "float32"
label_type: "long"
batch_size: 256
epochs: 500
learning_rate: 0.001
model: 1
scale: true
normalize: false
jaccard_k: 2